### ISSUE TITLE
Mouse position not working if body scrolled

### ISSUE THREAD

**Issue by SilviaElisaAimone** [codrops/RapidImageHoverMenu#10]
Hi, what change can I make to make it work even if the menu is in a position in the body that you have to scroll to reach it? Thanks!

**Comment by crnacura** [comment]
Do you have some working code I can look at? Have you tried to solve it? Thanks.

**Comment by SilviaElisaAimone** [comment]
Hi, thanks for your answer. 
Here's an example: https://www.vancode.it/playground/
I took the dist folder and just commented the inizialization of locomotive-scroll in the js. You can see now that everything is working if you don't scroll, but as soon as you scroll, the images are not displayed in the right position. 
Any suggestions?

**Comment by crnacura** [comment]
Thanks for the demo! I've changed the mouse position function in utils.js. It should work now. 
Thanks!
